#!/usr/bin/env zsh
#
# === {{CMD}}
#
set -u -e -o pipefail

local +x ORIGINAL_ARGS="$@"

case "$(echo $@)" in

  "")
    if ! which opam &>/dev/null || ! which ocaml &>/dev/null; then
      my_os package --install opam ocaml
      cd "$THIS_DIR"
      mkdir -p tmp
      opam init --root "$THIS_DIR"/tmp
    fi
    opam update
    opam upgrade
    echo "=== Reminder: opam config setup -a"
    ;;

  *)
    echo "!!! Unknown arguments: $ORIGINAL_ARGS" >&2
    exit 1
    ;;

esac

