#!/usr/bin/env zsh
#
# === {{CMD}}
#
set -u -e -o pipefail

local +x ORIGINAL_ARGS="$@"
local +x ACTION=$1; shift

case "$ACTION" in

  run)
    mkdir -p tmp/scratch
    ocamlopt -o tmp/scratch.run tmp/scratch/scratch.ml
    ls -hal tmp/scratch.run
    tmp/scratch.run
    ;;

  *)
    echo "!!! Unknown arguments: $ORIGINAL_ARGS" >&2
    exit 1
    ;;

esac

